Car_marketplace/urls.py
from django.urls import path
from . import views

# prin punct importez views din acelasi folder cu urls.py

urlpatterns = [
    path('', views.PaginaPrincipala.as_view(), name='home'), # acel string gol reprezinta adresa url unde e afisata PaginaPrincipala
    path('item/<int:pk>/', views.MasinaDetalii.as_view(), name = 'adresa_item'),
    path('about', views.About.as_view(), name = 'about')
]



# .as_view e o metoda care reda aceasta clasa ca o vizualizare reala cu vizualizari bazate pe functii

DjangoSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Car_marketplace.urls')) # e apelat urls din Car_marketplace, daca as vrea sa accesez asta la o adresa anume ar trebui sa scriu in string
]

Car_marketplace/models.py
from django.db import models
from django.contrib.auth.models import User

CAR_BRAND = (
    ('volkswagen', 'Volkswagen'),
    ('skoda', 'Skoda'),
    ('audi', 'Audi'),
    ('bmw', 'Bmw'),
    ('mercedes', 'Mercedes'),
    ('tesla', 'Tesla')
)

STARE = (
    (0, 'Indisponibil'),
    (1, 'Disponibil')
)

class Item(models.Model):
    masina = models.CharField(max_length=1000, unique=True)
    descriere = models.CharField(max_length=2000)
    pret = models.DecimalField(max_digits=10, decimal_places=3)
    marca_masina = models.CharField(max_length=200, choices=CAR_BRAND)
    autor = models.ForeignKey(User, on_delete=models.PROTECT) # foloseste o cheie externa, care e setata ca cel care pune anuntul sa nu poata fi sters
    stare = models.IntegerField(choices=STARE, default=1)
    data_crearii = models.DateTimeField(auto_now_add=True)
    data_actualizarii = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.masina

Car_marketplace/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item, CAR_BRAND
from django.views.generic.base import TemplateView

# puteam clase sau functii, dar clasele au cod mai putin si e mai clean

class PaginaPrincipala(generic.ListView):  # reprezinta pagina cu toate masinile adica cea principala
    queryset = Item.objects.order_by('-data_crearii') # minusul inverseaza ordinea
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masini'] = CAR_BRAND
        return context


class MasinaDetalii(generic.DetailView):
    model = Item
    template_name = 'masina_detalii.html'

class About(TemplateView):

    template_name = 'about.html'

Car_marketplace/templates/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<head>
<title>About</title>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">

<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
.w3-row-padding img {margin-bottom: 12px}
media only screen and (max-width: 600px) {#main {margin-left: 0}}
</style>
</head>
<body class="w3-black">
  <header class="w3-container w3-padding-32 w3-center w3-black" id="about">
    <h1 class="w3-jumbo">Sunt Ștefan Semelbauer.</h1>
    <p>Student si pasionat de tehnologie. Pentru mai multe informatii urmati link-ul de: <a href='https://www.linkedin.com/in/semelbauer-stefan-009675187'>Linkedin</a></p>
    <img src="{% static 'pozaa.jpg' %}" alt="eu" class="w3-image" width="500" height="500">
  </header>
{% endblock content %}

Car_marketplace/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <title>Magazinul lui Stefan</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-secondary">
            <div class="container-fluid">
                    <a class="navbar-brand" href="#"></a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                         <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                         <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'about' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}

<!-- JavaScript Bundle with Popper -->
             <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    </body>
</html>

Car_marketplace/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1>Masina visurilor tale</h1>
    <ul class="list-group list-group-flush">
        {% for masina in masini %}
            <h2 class="pt-5">{{ masina.1 }}</h2>  <!-- daca pun .1 arata al doilea element din tuplu adica fara primul cu litera mica -->
                 {% for row in item_list %}
                    {% if row.marca_masina == masina.0 %} <!-- .0 daca e egala valoarea iterata cu cea curenta se va afisa doar ce urmeaza. marca_masina e din models.py-->
                        {% if row.stare == 0 %}
                         <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                             <a href="{% url 'adresa_item' row.pk %}"><h3><del>{{ row.masina }}</del></h3></a>   <!-- pun <h3> pt a ajusta marimea. cu del se ,,taie" masina din browser. cu <a href=""> am inserat link-ul-->
                             <span class="badge bg-primary rounded-pill">{{ row.pret }}</span> <!-- asta e pt a afisa pretul -->
                         </li>
                         <li class="list-group-item pt-0">
                             <p>{{ row.descriere }}</p> <!-- pun <p> pt ca fiecare descriere sa fie diferita pt fiecare -->
                         </li>
                         {% else %}
                         <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                             <a href="{% url 'adresa_item' row.pk %}"><h3>{{ row.masina }}</h3></a>
                             <span class="badge bg-primary rounded-pill">{{ row.pret }}</span>
                         </li>
                         <li class="list-group-item pt-0">
                            <p>{{ row.descriere }}</p>
                         </li>
                         {% endif %}
                    {% endif %}
                 {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endblock content %}

Car_marketplace/templates/masina_detalii.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1 class="pt-5">{{ item.masina }}</h1>
        <p>{{ item.descriere }}</p>
        <p>{{ item.pret }}</p>
    </div>
{% endblock content %}